# Generated by Django 5.2.16 on 2026-07-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_name', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField()),
                ('level_name', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('func_name', models.CharField(blank=True, default='', max_length=255)),
                ('lineno', models.PositiveIntegerField(default=0)),
                ('traceback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'app log entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='applog_appl_level_3638a2_idx'), models.Index(fields=['logger_name'], name='applog_appl_logger__7dd6cc_idx')],
            },
        ),
    ]
